name = "top-ten"
compatibility_date = "2026-01-14"
main = "backend-do/src/index.ts"

[durable_objects]
bindings = [
  { name = "GAME_DO", class_name = "GameDurableObject" },
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameDurableObject"]
